### ISSUE TITLE
El link no va a una nueva pestaña

### ISSUE THREAD

**Issue by juan123sebastian** [midudev/noticias.dev#2]
![image](https://github.com/midudev/noticias.dev/assets/122684235/22341e49-7814-4271-bf4c-1b1cbd75af50)
El link no va a una pestaña.
Debería ir a una nueva pestaña

**Comment by programmerKFH** [comment]
Entiendo que se resuelve colocando el atributo target de la etiqueta <a> en blank. 

Ejemplo: <a href="https://www.blablabla.loquesea" target="_blank">blablabla</a>
